version: '3.9'

services:
    web:
        build: .
        container_name: another-github-badges-web
        ports:
            - 3000:3000
        restart: unless-stopped
        environment:
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-1234}
    db:
        image: mysql:8.0.28
        container_name: another-github-badges-db
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-1234}
        volumes:
            - database_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    database_data:
